---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-custom-secrets
  namespace: argocd
spec:
  encryptedData:
    oidc.pocket-id.client-secret: AgA1ftiAKS07NdwtjbUZABJyOX1dVJe/XWhgGs6JbeOefnKNpgsr0ykZ52t79gGRb/AxjsM5ik+GEx6z1LuZDwZuQhxsJt8S0YyPvOASYJR2h7bC6+qbzXXvw6l6BHZ6ItUMAPJoHLcBzZTurMl9niZoRfqUzvTS8v6Ose5Usv6yuX/smPLHsHoBsTVJrOSnN9SQrNzIkKP+LsdBBuYbuP8yUv30zMdnCC/mTTC595xm5XliHWwre3W+BAaHsmyq8vDYeR42qGgFH70H9XN5wtj8yRYF/VyrqK/25wAZPv4Oxsji+tOlBK9vORZsuniAuYiDXEws0IC1PMdDFP2Y3Sw8OFr3DudYawE47NnGCXLXdne+wb9bC2qfhRuZbceGiSjl3cfscj9Y/tJxmK6UYgvRZA6kEQrA3kSv0xTxJfV7NvLkilbO1g4Z/SdOVXlKgrYqF9FAj+LAtAGaikAN7wrS/r+ki/gJz5sIQxSK/DAix6U7NpFlEPalmUW55MzYxCGXuKkgukF8iItitPpKkUI5/3qKkdvuj4LdcHcqnZLPGbC5zQtQtD/PA3fYse6/+7ru2Tn8g/65f8y8fXN+2FVHaeGp4WVl0CQKXVXOBKCEoPQ7tDI56GMTalYNrQNTFVO/XSB9EsxSgUPSlulHCnV5M+SsdyRsHtpzc479EbtxRI5tgfjhpja/H6N+OnGQ8YgK4MJNkt5LV9PTExlPvlIHrS0UNDMxH5mt8qgBH5tuwy4=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-custom-secrets
      namespace: argocd
    type: Opaque
