---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-custom-secrets
  namespace: argocd
spec:
  encryptedData:
    oidc.pocket-id.client-secret: AgBJpjBr3zk4vaK14eZHEYKDzQWrgIFuoRDdO+R6+IWlVZGqMyx6YLjf0fgS+FJT+Hn7YBuG/fGss8tJeiCKXDcOXgZbKcmy7YoocfvKouAW5PAAa/chX+SvAVamZ3SSyTBrjVr2Ob9Oz0Sima4CMjpr2fFZV1nn8gd1KpYpki+e4O2ZYT8vhsQ5OWCmDzAd+a8YyI0J+bKoxj6ATcbrM1Hfcl6bC7Im4PuuSYAOwsWJWzjQq5v8bhjLGJ05OErd3iUXh8lCyoqxZ1iJaGQg/rRM6mixbsnHZKisdQtJyKVF1ZNRaJ5gqjA11YDvxTZIO7nZLqDkLAnErov28BBlTPdffNnIjDhnCd2zC5NBk6bkzDzD2AfHoucTqNUFiAErp5rH9ad1KyUmhY6sHcIgt8wiewzLzcl4LGURBRHm45Yg5QNTsWWMH/tHCWxoPET0OeQKM+yAQGXCLQeQsmNwRuOh3hAAChGFiwEc8+ggD7Jw9SHW8N/fA+8dwwlHqu4+Ib4BW6XBL+RbtFuf7EARf8pZgBCHuzTcV6DXp6ijjIabmnen1po4gbYDp4XN0LwrsXtUELHXRG/c03FAfhC9VA4yRqLtomsWqZmOgB0CoRd4JF8ciOYrHG2DIfSMGnUfVQRUTZZMzLvaKjrOsyNurvOD+877/u7PwnmEgdLraUWoaWQ7RFA4xb1QF3w2Xu0t1P1MJm2j7pSdwRup5jrYaJmG2K7iZFSfTvNSrv0hqIHikvE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-custom-secrets
      namespace: argocd
    type: Opaque
