apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-github-secret_sealed.yaml
  - argocd-custom-secrets_sealed.yaml
  - http-route.yaml
  - ns.yaml
  - repositories.yaml
  - dashboard.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.4.5
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml
