apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: adguard-users-secrets
  namespace: dns
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    users.yaml: AgChvkuylSscvjzajFC4bXav5EJD2anXi6GecjL+PoLvKdBBn781b0QgfI0kGUM9ZGCtR6diOYPkcGXKJTRHMONvylzXos1R1VaGVu5trKSpsg7nP6+tSfmdAU4NOvAUTxabQEr/7HCf6lzhv4xSJHFRv8L9QUyhUOpOfr+YZ6q5SBe6UMI7nJ751NpBbV3L7eqCsLuYuC8L5V3LhY89C85xKTR3WQRsOMG+xEvLj1L1mNRBFT63QEkXrGeH0no3/THTJlCkO7397Pxd1Vb9iesCATXFneMUEX9iOKazs6VqmDZh/Kj4dywDuoR1LBzpCEQoAIJmIGkS73o/jxGyKtfmyZAYadx06z7pUYH0BWwZXpL30xWHP6Rc2pN+V395S0eJFQmUcY/Eqw/e9eHL6cDNP/p3b2GXSAutAWHB3BptIYSzydZ151OaW4crpXG/n8WdtRybiMmyJYGdB0m4I0PawIOuCCn+WYJ5q1T+FsZpY3eWa5OIBU5xMT6tSmbz1OcRg+VMmOhi9tS8k8u/TmD9x2+7PMjEzV5ZxXeykox4uf9JrGygVVVheDhAac/chaBISoi+vDRl3P0QwvdGh0PwXJueB0ctOtK4dOd9hQAP8YZxFxWoU9TyknczilW+ShKfWCMoTlZ0hiCzlljyyeA50T+9hQs4NFrEkzInQSds5TFyyPK1TY6M9XocEGcmT84zCqCo2EfBNuh/9X3cZmuZVfneBaNNVveZmh5ggpKlO/KMw7cjO24hQjGBhJYpFk8zAn6WuQ6EVFMab0DZtZBjesacIn5rGQgo4+Ubxm9nRSMEWq43hzFjmyo5X22cNCm+GA==
  template:
    metadata:
      creationTimestamp: null
      name: adguard-users-secrets
      namespace: dns
    type: Opaque
