apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: pocket-id-env
    namespace: auth
    literals:
      - TZ="Europe/Brussels"

resources:
  - ns.yaml
  - lidarr
  - prowlarr
  - radarr
  - sonarr
