---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgB4kmnvmYI/WKz/wBUPgIux2QSFLTsSPUeEgF3DmaaxT5wZCpdp8upb0uCtCIpASj6NTqXvbKqA0L0JXLFGSzWmxVav77lva72aS5D71Hx1FkqekkadsuAW22UMG6+Dho4/R1gTsW/dFAc300ODSDa8wFXPV4TwSn1wiLeA2dXPkmaD3tXqVtKSiYy/YCk7qRqW1T7D/dLlhUB92UiyfceXBgp9OK3I+s2TA9vV4nWRpz1uAegUJyErlAamc25YZjr3uqK4uEybmFDW+DYwAPZFZd1spXyK0Std0ZSl8oBEiVGq01zGesNN5d/zBmkutT9ChxBZAQ1Skr8xbpwc3Nihmlw/W5M87sWFskldI3znYqqNadzVv/JDKlpkP5WR29LDdc+yGvgxaEXPWNH+ndsxR+gMU4EHYmUwYGJLU9wRlH054G72T+uTaSxWmTWF7ZBMlPMTNGRjhwkuUwqw7nXLrlmzvxpH4yp3pgzISYQ0SUdohhYzXo/DX9HhkBT+6yP9hdlZ/XzeuYuBLwARF/27xxyIRiSV4rxmchu5D1BmnuZjqEZAHcGzAeHDB5aGt1NqNjTwzLoimhpUItTWEtu7lAjrTVG2GP2NAMqMMEi0eg0B4JcQjaJ47cb1lC2ctJX1A8t5DHq/894Hj48GZIDxJ4+KvqkojXdY6Am40FUreoiRlRYEhkIpQv8W7BWeiwMELb9aiyThbgS4HU+BrlBsSldzNPGrL51Xl+EJ7Wqy23eaKBP9O1pmK7mC/K3brg3EHkGLYcY3ipiqy7An16+Z
  template:
    metadata:
      name: n8n-secrets
      namespace: n8n
    type: Opaque
