---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-superuser-credentials
  namespace: n8n
spec:
  encryptedData:
    password: AgAwnXLo8RBo8RYKNXwphKLIdqpGikt1kiZTptuVRzJLNMRqneidyfoHdCGEQc6bHb09HPkIcNF1OXprXIy3SIzxHxvPU07fDLsVrvH4O51fuXZrdHfPyd6Kn/QcDoZE5faPm2VkzAu+oNJ7Z3l/h5kZScGfPT4Hlu5lY1n6DZYqANgR6YgY3v60sXGkCKuBT/GRt3oEyVvgaZBcF45ymQC9cZh9xW5JoJTpsprRThrh35W8UDRBaJqTy37LfYG25EDkiYXVT8+rEi6ZI8bXMDiWu9wSQohtSbnBKFTm0PN895dJrm8JjI3KyncZe/TiLLn9oJqqdCYhDLb6+cUM6r1QiMVDTKh8cV6CDCfXxsUq6FNLVywtm51f70wJYCTa7+YLRUAJBGgbI+tME4hCiVwHQB66KiZD86i3cUgVBkUjJzYjVJEDwSVi5FzyO/FdfG2jURUcRp9hy/AI9Wygdhj9hxSwVjk3FGvFWQAVPfXn6HhGeZhPdCpNgtcKzPSSRQZ4qB7mAbYSwYXK+EHpLP2n97SrwlJWqBYNWUfNGoy8XHMmli+K11JRi5WTXXziAnG8EN2nMy9fxggKlpoqhMSiTRxiiU4q7LsBTRS4wRknp88TAp88pYGHYpqQJCW6D2t73FyRIBjQ0mok7a1UlvYvVHbUcUBmGz2tvR0fI7osIOPbesH6XLCrZmAlACXjwgUcmGstylKsdiHBDHu2H7cJDuKZKxZi4giVbFdAzwHU9i5VNyfYtDuYqfwecQ==
    username: AgAd2whS8SBAET5fj4z7CHm8fPMJUAFS5HQhoqO4tBhFBHfiYFuuRcIkcwBIXC6N2qv0am21RWtXf0Af6gz3pjXK+zZET0o8+/SM/sWJUG8tL2hVFVtCLIyt1NSfFMvCfyn1VWgQAtpJCr0BLJIpclXi5A1iwhWmoT0w95e5g82ZBp59K1rHXltb/AqjGwjo1RyByATVelg6XwqxhgkBm46ODocdLKdsBBFpkhaqeHmlW1juDWt9a0p+dxLIuIBXtjtGTV+MNx1yv9PZZZvJU8GYYiIEAiFvjfo6Vs/8CLKDtXJs0muESFChcSB7IOoxpy0zbtMyvRXudN1hBMgoGbyjJLchFo3tZZxES44sWrLSopT3yaQb9eY7o4MBSy3sNWaMpvQ3TEytoBl0VMZduzDjNGHwfNS14mJYMc3+BimZEdN/shAzx1YAX2762Wh+3xrRQEYh7QBDkTrkLNF1yiHBtck2XEoy84iU8akycY+6U8r/YaYm62nh/rozn3X+XdEqO4aRSDiMt7dmRRI2xJPW7V+pM+eFeXBsd9B6cIlULSUOCLJe/Gr849Nf9FGJ+UuchUieSXvV2Uo/PrxMktDfDglnwyy0Wah9R28iygTS6QTcJFco78sdG0UhLlSwQLh6LBTAHkteK98SYMF5mYVkHz3+16CEoMWJXiqvQbDzXg3rWVjRA2ZsTpx6bXuvrxbJ5zMNQzCoSQ==
  template:
    metadata:
      name: pg-superuser-credentials
      namespace: n8n
    type: kubernetes.io/basic-auth
