---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-user-credentials
  namespace: n8n
spec:
  encryptedData:
    password: AgBKssiosJgG8vsq0vC8vd7I4Bsmm5LnYsXbFg9d/jaYeXbydBSMAZ7AUE6elSzjYkaoK2FH9hsjnJsUlO5pyqEScmVnnQFBFZd3gnSm+RsccHEsp9i2EKCGWYJorhvMsh3hM4ZqbBCo3QPsblxWTatPt7J7/juBISTnPyzfNI3AyR4gcejUG7UHdp1+IgKH1mnOx4FV772rGRfZ7UNJthibEEigMNixEXiEYYxsQaieG9kDktPGS72gvbQw7yLHzgQaL5QwNc8Sd76BjpdFMivcRFUTYAFN+QIbX6Vo01hSn/BvQNDIBh0O74/pVsKodvtgxOqUZ8UV+Lw95moyAzhqeFyFThJiE5Z1cLx8P7xC7EVqh8yAjGz8xRy48J6GgZ5mSfAgKI2SuExLbmEdvsM2dDYXux5nG6iNdh/OfXmyO3T8m/6gF+VTzjeuxcqX0U5AzJllcV8He1itzWWO1TaBj1XVkMKfYjg7zAirhvQ4yWjIqW+pF3LPfF6koHZpWcyUnzcFoUWMgLW+6IjRYXz5Im4aYKXJoYWniIqYqT/K3yRAFjDRsh0fz9WF5h7pt8J4/jMcC+ydTQ7o5U7RVH9k7pbkX41dpafST+V3102m9ljnxP1tMDz5oem5MHDlTNrLWosb3OjhfPi2ffGWzl8OwFShZnFCpV538zAHpH2Y+ZyETRm0FkcMDyWJildR63qXFGAC3kW68QcUyEIflSMYTBrFj3kHfAfWfmAQ9NVSIFv85VkKdRZl5dm1Qw==
    username: AgAQ2VqdRl0xbC5mau7Dv2+7rIcvMZnaAIuxufLTDyaJ95Wtzsuijx0wAQxyb1shgrH4sPYKpsoHyGUrWS03MIeYH9jL+FomJKUeiq5CYXr8vL+dIFneZW+dEDfML8iDt44RHzgape0J2v1Ftl2sgDj13lavlvagkWB/IhehGpyb7cgX4artEZBrj1DwdSi5ozr8E8xWD0vfTkJ0lJZMdTZGfStwtUI+ZeXIeGynYJbPFnzBsLIwIqSyowAhKZhwKGRtfhe9tlyODMJAHyhdPIrx5kOpJDCI5kejlKzbWdR9Otlq8lLNmGf0AfImmBxIchXjvk3z9xMJvAXKM8VMLnl9UKptLPokgibz97Pcg6HVsrn7ZhJJt3xyzlvtA2m0xzr1TEuoZQ5peo/alxtNUhMn8oJlps7KS8bMZmNiz3w2jSKs7M7WFOG47iqGt4hW+6O39ftfHUWAcMZRBxtT61H+MmMxi9PeCuFsjRiy0QOMO0yMjJ2+NeTONj/X8pcmLre7ivC6N+jTlrZV+pO1AkVfG8xtpYlCjxTdcDjBDjU0YZhg7sDOpCyOEOFOS3xy6Zrdit5wNGIGY5aVmGRzl70xwbCl6nPpjAvfXJguRsxkewzGoCtN2XAFtqov8HDht7mbLBnhobVQMIjI3i6LUCq97SsayP5s59lFXPSX9RupYC1jj/LGeEvfGNKBOGL8t41ttZ4=
  template:
    metadata:
      name: pg-user-credentials
      namespace: n8n
    type: kubernetes.io/basic-auth
