# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: grafana
spec:
  encryptedData:
    password: AgCE2LIHt/p1sm61gOcGA/cb4/qKM25/oPTZav90CX07pqV4Y1zK6K9CZgwR6S6W7cTrPo3dMDaCe5nZM4cC8GyR9rJ3HeKav4HW6JrnbxbYUor+O2X6HatQ+Rn0il508uvuD6JDDAU7KacnQoFnt8BY4J7vdCfZUQW2en5ZDiCDC2ydC8wNRoE/e4Wfr8iL7H9vJT+chwJ8XW8JV9wGa9EwTGjAIfZ3mESB9PL0KkhHVeWqE5iStkyhDxoNujVI21s+Q7AoaSxLbEtoyGl1f3rfoVH22TJpzM9HeS1zx+WaypyzuKPAcLr7/byQ2+fVvieo4Xi6d+jBa4qym8s/Scw9CFANcDkNTKhzvQ/RQxs5/2fBtl6t4qPS9l95egyfTnL32nPSeomz6OKtYIrHeo4HPcB6RY524VmV2Ak55mH+XqqZJgUS2+Ask+s7W84IZ3qATxiRWFbNJHk2g5wYAxV/53TfQMx6y+knziQh+hmLItbLo6OiptM1/5StJAOzxpIFkEO88LnC09yUaqJTTrgnl1HW476IKDl1Dl/YmERjTtr2OjE2mq4nbHQsFf3D2V/gW7Y9izNDiAQRElu8S2pb171cL1lHGGoc9i5xWCXhofSlGFy6iYgz/yo1yWUoN0BWkIgWW8rV3fLDR+aiVmkL5PiZ0ifIHCV6vTy8IRYWzVfK8ZkZpi60ggYBXj+fgveZx4b6nw==
    username: AgCkRYusQ8UhCxy+vK1OT+pGZmJ2cS+aN9KiN/wKW3t244NRoEEPP5kVBU2Fs4Zy9XuamU2jBWitQlx5PzL/boqQkXtYDWcUqzEgzivhi88FMU45p8FO2NvIuhczQ9s5gPI6vvvkpZqJgPnCcFhWpwwziv/yZkqqKWOOpL9khshoHSl6QPG3SwnQcpqV5By+8rqg5F5cWOmaqUHNi9jiK3udvLFDHsbWdejmrvJBjM3tYtWWwot+OwjMGZjtTaks0URoCTZSIXwk1+x7k1I9BlaFx7qPGcE2ZWP5hknpa+PuWZmtKgFd9XRvkbG4D8s88N6i8KLE2hIk87TUUmnlMdzr0KtLcj/khHm6fkRmGGaT4MUX0Lc9A8+xxCdWkA6lR7uwJMlC29v7+aJhc2ZrtTPxeFT/rQ3Pws9mTeI8pEBFa8U3BkiImBgYDMwgMm/2PzNGaB0jbpOQtLiBLLEccZx1/nADzbXl/7+7bW/6Nrps7sXYLT80UWWP4P+DhOF4a2YdZHlxlmcosJo28TAB50h6KJT1n/ALUDCqvxCczn/wHOwFNaOAVMLwm8K5kem3l0BobFgEXoVXkF0nsoJS6sK+9xKrHwhwV0TsnBVhFe5mHyHM+vm5g5OqLW1aAz0CIN08+Z9+cZ25SzraKIeLclh0yQQSl8wUZbizbmE7wJofwWnvL//sculSgrkhSe/+9jOCxyNTrJTzrXlcv6HZal4=
  template:
    metadata:
      name: admin-credentials
      namespace: grafana
    type: Opaque
