# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: grafana
spec:
  encryptedData:
    password: AgDBN5p+DU82LzMGMQEdJUUyQTHMbjyy+xsL3BkK8RRRMXT/Ir4ioDjUOJjbwNTqvumuRayZ5QLeezoF8/6XZ9A1qYZ1LQvqCncpl8TRGXqN//F5+Fk09R3ymT0YOIPQ+iq2NU9/sjSdyI3hYkkgsIYIHwhiyB4vWcTY8WGnrSDbMvey+xr7Tijh3NSmzN84qwLURbKkV31cJgeq5IpN6hMDeZ51Ft2aejePuC6ueWo4E1rXjIomXg7tdAFcvPy8TvSezisdmLUvfp9nYczTiglRXaHp9yXHnCC4q7vrw/uXwP4JnT1T+xpotc/UQi6Xlhu3coVb8CCVrRFih3SR/T7MG3Klho1HyKce9cEnGAPR/qxVt97yLVrbK1NqBZeRj4SIsNGzVg8/VdJZfrrSvLeDFwa8ddbZcdcm+hBv4S1POTDLGpxTnvGI7+dF4PMWCCAvrvDNF3mIVcx+Mq7v5Rsxs6zWWgn9QA0EKVS0h/mhNe5suXH1RGjx/Z8MwMWTFHOABAhlHoSP7oRcVZ6WqKrKDZN3z96aNeHk1mz2MkVWtlFetyBgJ0ZtTmLXYo4XKPypZggq6/JX+ed2wd1VK2o4BLJbZA0242e90fBhzzS5BHzVjYo0o4C7rL7AD17FiwAzJn/Cw/bLd1W0pJoo2+pf9Nk9paOmwgP2y8X0nK/WFXpN0vMe4h9L5Pf7lKbst/z1o2h2h/mBd7de+vUIpDk=
    username: AgC9g8mNL35UymIHMvHtmHx7LqKOuWqRLnWs0+swE8sDiKdYTnXk7hqHZjGBxZzS7QckNDF4pHwckN/dl5S4dP6YPF3F3Duv6AwrpZOzi3lcEAzBSHNEHYDUyj0AwjALMEx4z/d5xNQbGYl5pL9k3BF9g/yRFf/V6g1zpgfWjcC+vQi/84NdoGredug3M200d3JK4q6YsJ91wtnBvDTl8pdLUfPt+hwxDRxUcaRWsOEVBHGFQB5hvm8TfcviTV6hrPUwyIPSXp2LL208rRy12v9dNc1Dx8I/71yBH3sgHEBSvrd283Y1L3Jqg7xz5aELB0BhIa4tEoi8NE3kiSFEcLpzpe8E5Wo/S39O5wqDo0sHbsvEisIAPr2hIdtc0isSw/0NAeXD6RCCeJjqXMZ5rsbi8+0/LAyFQnDxqseQ7UO6y4zfkOFtWrx4Fj+Xr3wmkLdJUUvdrTD3gL3eouS7q1hfatEWwRiIRYXtbrRqaD91A6rZmBdAR4K/Ut1hppCzJY8MZ4x3UBvbPCHRlBWZAO5dywtiV+oioBbu/hBWXNPwqs3RoUa19DfrAOo3QZk2ne7uxP5VeephZ9aJa4KC0zdU9FI2eUOI+pTlM+Ikar7ICnGhuUKI3VBP16o+p6Exxq3IxkXLVUo/bYRmsN+OHyNwulKCrXMVx1Vrz89Pz/TUj1dFvIbGW29Z8wiw8CNj612hj5ntGA==
  template:
    metadata:
      name: admin-credentials
      namespace: grafana
    type: Opaque
