apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media
  namespace: argocd
  labels:
    be.ghiot: application
spec:
  generators:
    - git:
        repoURL: https://github.com/cedsbe/home-infra
        revision: HEAD
        directories:
          - path: k8s/apps/media/*
  template:
    metadata:
      name: "{{ path.basename }}"
      labels:
        be.ghiot: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: media
      source:
        repoURL: https://github.com/cedsbe/home-infra
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: false
          prune: false
