---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-user-credentials
  namespace: pocket-id
spec:
  encryptedData:
    password: AgB1nrV8yCdUx1wFoDgu3DhVneOwA66sFeE6P/xp9WCz7fnafpiT3s/u3gjNFnrwjEog+YxhLGY1CcMWGXsWt1E89X4/e3ZQOxwdg12FrNGpJ7Qp+AggaYu2c7fV2FLsKAscG+UKB6b2Ni3yCMAwaxoMp+CbZOqSFdssnNTRaA/rhz8w8uegtaIXZCtLb3SFJb0Oqlb5e1ZOX4P66ZHRnwv5zakME5B8ZjMJGDaI6cvonQAc0OxBATW7qIDb8SxwLZeZLWWNWo6WDk5d+8i+FXqo8wnYtlu1J0DP+2CLTWbr3P6rNnjNV6ZJ3FTEC/GVwFbjXmcjbCQ57rM1Hjh/3BRRwHZQgOg+Bc6bOgfRuyZ1HI9fuFc+5Fjd3hjgHfPluqNmQ8QSfhsu+Q9LBRCbKpjbCIwrVuqhAjZk0+RUUJF3A7iThnom2tmE7ZNwKjOcmKoC2JmQGEuJDr4+LV5NI48CR4WGxD092XpSiOMjsLvIWJlNGLb/eySYtbuFpurm6A/SBU4lCvlCLe+nuCYbvxJ4R0yAT4w6l52Xl42liOLC7EaMJNyhy22HTUhkD3cuvC9YTRmZk2/gE+rgHxQ5V43+IMx26NGC2P+m/Dn98ydhQSCf6P7SA/OXESyp9jv+Ar8KHy/vWyeir+2GWQ8Qnj0lMDCUghvQAb0XgZ/ytigiR6As8xaI2Qgs/hxH4kH1PSe6rjNmRSXo/Iac6+Ajl7wXGpe+ILuryAz0OmsLdDxM
    username: AgBhuEgVB+IcJrK84M3gz4LKyNqcieb4lcDUTwc6WgnWxB/b3jcALAPobm1U09HztRCC08FlxmGX+lHMiGk4yffxZJFTDY4sglode3G17yZhhHmBI+dwu+oLTivwcS4J5SxGPIjCjKMF5eQ+WdTWDk92u3h1nLA0lqIpvV/cLceT+AvlvQ1gZ1ERuI/kvQTZaAyz0L3kxNwVD/zzcGoI8ud/p6py5jLxkptjS8CJxrLN3F8XwllaKV9fBqTAIx5qrtC9NPL3S00/8bKk5HQCE8TnVu+7M1CktVT/6j9JJCneJu5t6KwHYEO/yVFhkkzdyZgNorjKO7734HWgE0zVCmOWPcLS7TiusyaUKYINNGN+aTXOqasNXYo31tH7xbHFQx6uA1u4XgdUEVIssUsFJevpNac60ajRe5UJ/1N/6tXAuEa9EvHnuQTnXaPDVRjMYkC0bcK33ZSwbEMTnT2KfjWYFvFHqMyDW5daiF9JoareDxuXRlEznFHtBAP2S6JPaEPXwqDH42tr41q4fV88mAYfrNikesX8MRAxwaxHkCOy4ClBp37TiF2cHAWvAaMDzDajqu8Hf5GANT7R79LrPr2b9y/q0qg/dOwcfyUbKszKzQr5mtGCD6TX9jQZ4SL9X1+9a1C+ei14mE3yC/3gAzKpsl4DnrxRbST0Q3fhh8Zao+rEAT5nHw+l8cvfSsFCi6do9IC/dKGpkTztG0bi
  template:
    metadata:
      creationTimestamp: null
      name: pg-user-credentials
      namespace: pocket-id
    type: kubernetes.io/basic-auth
