---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-superuser-credentials
  namespace: auth
spec:
  encryptedData:
    password: AgAWKdiXAUwf9EHfpqO/qWD1Cu5E+zucBaeK2c42x+krDKkSW1NViYTf5zSE7ICpTfB9OrnlWxJcLQfRxapuD0uQT4oJYoIWTN5GwoJjmGr0T6hKo3qPTsJ3j48I5gn7LKp9aFfsrdW5RTOsAQoPohqOjjSSmEIFQDQBOr4L/TcjKPXScBVGJRL3AYS/wnalGZy2PewEXIu+yjLl5uR//SK9aPi6UugP9BAVziQZAluai5ifpIDNN+HWH0pHd4HBslmr3I9V0gOjxglI3uQP7jgsCkaKCfyB+lE532lg+O1WCALC6ruBcz08xoINzSBlGu6RpyKTQgOwTkEO09jm9ZtaJs+QaqUw4ttJjPGuFPrcvUKY7GMj3EglTGG+jdERF8NbANRbY0ZbBopv/K7Wgi1YMzB4b0wFLXc10u0clplbTJ/FslK7KudXI6xMItYx8SDQJlIGQrGqVRBVnu3TVKaBHB/XznIBqhfBPfg8nSItMrxA1NX6QNFqz1+1oIrd1e0aynpriF3rkvZNJeAqcjoOm71vnx/AtjI/x9HcAuuUYmhgdaBRcuOh/wIv9h9Jql5d0llcpNxfoynC6qhNXEm7aM36xmLKhaeyK+gSrJRP4/HWRaUQ+W/EcvhVPRGSzqOOkrQe0ncmDVCOmMWdj5RznEdjNxshqTmS2+Lalh0vRKgZQIRJ1kaTxrjcq06X70CrOhyn+CuqWRaz/Ffbtsh63TY2/bWONCrLKKlSA+NT
    username: AgBcVr6ucEnYGhAU48QmPycIyZJ/SDjaJgol4wK56SzdbYLBmZoclZCVLxIQkZh5ztng0KjUi5GgKG2/zlXtw5PGNH2K3gp42bu5aZVVxOrzy4t1HOIqEOo1Uoo191QXWWk+HZsJDC55sBGE4z1rg2xzMCe+cK/rYvHLjeMk+kJrsPdIHrc792II2tTVOzWPEXH2+hF6dGqsDrYzlNsrbeK8tTiuZdKCDY7SrKh8FtdfnHieY0sK6wGlUBcKbZlXZ4T2HQGN46UURe9Z+H9wgkDHNv7Wxo5Al64fEfXEdXFCwoIab286eH2aGRCPWHj8Hl5lC9J2imwq3CEmacVKjdid6fG//pR/TGphZ3Osqn7ZrUoGep4JT0dJuW0Wv2Vr1PeGGkbd75kiSVgTCtKRGANjbge1xNnTbSSJHyRonKxSpTNPFRTJXnxz0pGZb7dPgHx3QAMNCZ51rPyk9O/YRpNMPwC/HzG8WgcNzWOKthzt3sdV5T0m/X4xN+Q+HnL8sJiDx8KKVZeYrIe3OGZTzsYSLPUFwEjr8XeF8i8dXaXTEU8cwhgCSOJNdvRIuc5LsWTFgwmh+EmGU8Gx9VYHtDwmZdirloGlonUYt2KDQfjahIdCe01k6XcLkzVoqAtXhE0+0x1YF/dD5wcx8e/EUDgQQmd4l7y2p+v5Te831WdaxqN3GBKFmHvvZxbu54AoFE0Vx+RAeyG5lQ==
  template:
    metadata:
      creationTimestamp: null
      name: pg-superuser-credentials
      namespace: auth
    type: kubernetes.io/basic-auth
