---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-superuser-credentials
  namespace: auth
spec:
  encryptedData:
    password: AgDfOBeY7nqmfYLDi0ngOlhR27oMR9jKNj3Hn+FFCNVEbGLEFB33HQgTkH4ZuUHl6LEV7Elpz8X5383gztEM9a/0d+VpsT9JsYjxvduQIOCHxXJAFimiNyQW/K7ZcJKA7NCPjZs6aZ4ym5gnu4EeWVS7HI6I1VQh/7rwGs4xKyZnwOSTMydloDaIL6/mvbDvFlhRFSXhx93JDRJ76xY8RjH3so8Ai1zc+GvEXv2p/7SrnHKBxUwdT0sUuG1ir/cUzFKQPcouJyYnuHvgxAfiZnLNVVA1V94rF3xC+rHksO7pnouciLgY29av9SsMTeIJiMsEPgYU9VIZDe0xQ+ZLE1wBjK2VwCz7IKJetuxDmydEOac9EUm2kirIdzEkrMZUZOpBaiobx/rXqMqXSsRVOxc8MZb2gWq7wwS3tnSGvyyPhK/u3Ig3IYt/48QSfBcBCO35G5CMXhoHfmgyIdbsqRAca+lVN+k4ys7A9RDqXqOBogCTKvo9sLmCKne+w7154LIhTdjXcgL4oxE2ase9AB00qPGp1GTYThWAyPJfCOon9gfmEbvQ8Wxn8K2y4XvHZtdovn07eDlGHhKQaAhQRmqR+yzklxNPdnM56qR8DykpW2DEMQFGV4IrE29XoBi7erdJFC2C+HLTCAtThtw7gLwLZMYxlZDEfOU8ss2+FR/S8tYshHrKltPz0/d5Vi6f+fKMBP2TA62LjML2IYHbcUSrhpnTJ/modNdlad6qAOks
    username: AgDjz+tlOJdcdLRfGDzQscrxHX28pH78/+JxoIvmtjLuo0aAiQozPQgihlFGBIF1uSf/lPqd9RZrYkFhl/X8hBYF5YmvKzxJVzfVoZ8i66in7H1SVJN0VwHF/CBxbjYcx0wZBT21ZZHhrihqyGPyDp+P7ErdjVea4maukw3EiwnJhSqdLOirUKCWh3F3ivr1wFPj2WQdZFFJ2yT9Rx6CSFa28+TAkkgdlbKCjiVJi6AOWDv22/ddQi1cC+ihiP10BItxmm4KLdQv1ZeCW96G+SvEvvgBuzz+tTU8WvspIxq1NoBSKDKEVCX8IXBGvVk3gaSkYl5Z5Pr2jmJ2K0ZAcToss7Ansdw4y02G35GoUSyh8Jnwm+xtKrxISDqRg+j8O7osvJIeDTxq0ICwuGrCv2ebxR2S8bfeyVaEglHyDi8+siYkgUCR6zRzvfFSV+1UfwoJv6YO6KxVIJJfmxR8oBV/RjL9SYdT7VodViXdxR2oGDoBG1Im12lPl2Y3n7kiOIOPXfGTNmTYUysnqwiN0yZBlcX9evXV9N9GSUPprK5yj2pfFGqhLOOynvQVB4JSYxNg8unBnDg4WVPD1/nhFSH85DCpQo+X6ovGxmORT6jnhAICbX34G7l6UrbIaJdDPUXzVNQK1xm9Nqh7ymhIfYJHbQI9FyKtJJib4KMO/xmUOlQht/9S8MITVsLtsiEQmHPQQMqCgL9yZA==
  template:
    metadata:
      creationTimestamp: null
      name: pg-superuser-credentials
      namespace: auth
    type: kubernetes.io/basic-auth
