---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-user-credentials
  namespace: auth
spec:
  encryptedData:
    password: AgACuHq5nLtz/twmzpGDWeNjTuiRUAJjx68VdAAJmMmVftA++TwsWs+92X+D4yPHacMxCjcM4doFQ/O6Ac3O1KrrTOvwN8vNigDDIoWbQx7FR19BlDQRpVOq2MTPYtXNi1VwnEsGGcjZcDS65wWkuRSf7pxUCbRTiXd17LiOCASIlfqiIJSsjd4uMNuEvM5ZNjAkehspdY54N6R/6JIsv2iGTSW1WUATozC6TQ3Yf7kdVlhhM0q+4QGRU68hTgu4gCMSOPBIIYmKTvG+auJsByHQcY64gWd19jwtCP4Hn7mHsD6Ht1XAJt0Knlkk5eFyehwtpRPWYtKX0CvjLWJymorKXVIXo5dZxpq62C8qcjck9PJHYhObbOvoS+5HSHEhKgiMw7FP7sO+N07IjlOAW5vMqm0wWuJazir/1VY2ds7cxfClj2WeO8Q2sF4T4EU4//ytLFALxxDW0s6JGwdYl7dODYnS8JiSr6z2qQum4wWWMi/XQ8yU5GGpVqedOF6iWHp1o7/zw2KDxyf5kq4rRshxIe0dfb6wVot/cGT04N2OzUnWbbNVup/uYd665LbsW+Kdvm3xATWkG+nYvEy0F4cncP9bLYeKRmgCo6moP8OtFqwuW52ufqyj+dnJSsp3TWXmdzOPf/+KXYl8OKn5K6C7lEIs4d55Z4nJBF/jzcKkdUYAPoiaeW2RvyPYxqYZqu906Pf9Aiv9U6jD+X8WysSrHoEr+hh5dg7TNu6tX/m+
    username: AgDR+7YlsBnMCw73yayyH8QoEKtWtnBNu+rf2rcsVk1+pBsexuz8yeQpX6NydQklwYiSTN92dpVBP9jLJpIFfvkqi5GFAnmhQymdI/8Crnds2iGnPtfYOrh5fZsa+wrfvqBJHK7QOEuiVh/h7dQ+kb9AQnCCLU/720L/bnGf+TBOl6hZ5O7Vafy3Tex4sdVVLcb63f0t233XqsBOWty+WxJUXlsDq1E0u139xHxsFEDeNFC6trkcVlhI+2sASUCnx1IaDAQ8YE0dClrm3X1RvXxyTue80hLImuFqjYU3PMZoqOIKxooQMUuxhpLMyrLzxjHZSrIYRTUyb45tA4MPoJ2zGZJ+Pr/yLAnGLdaBwJFjJQjv8pD10HsuUQ8Z1Gb3juP2wSHhvE9/CxS1VI/o1Rg6VDy9hDa3e75SQ0+xLw97fBE+1tz7oAs/okbuZjxZ+BzPyY22dOJlPYTniO8fVOIm7xauAqO6sAQ+1ecctVJCwLt7D+61OBLq4Eumldrh/qgjj6z6mCzLYKOuLm819ssxwbX/Mpg/YPf0DxyPTey9HZ99Y/Qio9yz7Suy6ZpQ8Qlhv0UtB0cCpV5CuEOzbyNU40MRWNY6+XzYDAhmBlNTiiF8PMzXSAOqAqw62jZ63oX9YFGiq7OJmzZs0wbWIDBUyhDXSi8u4RJ8FgA9Ke0FdMiry44X7/Qkk5WK47Es6UTnS85OnS58DWEA6ESa
  template:
    metadata:
      creationTimestamp: null
      name: pg-user-credentials
      namespace: auth
    type: kubernetes.io/basic-auth
