---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-user-credentials
  namespace: auth
spec:
  encryptedData:
    password: AgCTv4y0c758k6JsyD+nGCc6WDvH+ImiCgmUbZYn+dWHlGNA65CRSarZ/HHg3dR3ShMudUEFgViDyuHZMfvmXQam/TUh1IqGQCuMuujtOCAH/l9NjO5l2xaJ6rUE6Wk2vPLXSD1IanFURMTYiTfs56HJa40vuJF1BFeDp1Fk3YhH/B9auRFPDKqGWLOKmAoTtiEp+Hv96Yeu5JhVnYwqRv7XJiDFZgqjLPkozRuwkhgzHnu8EQLeKp86RIkZm7ZdSO5kXnVn+Vv9tPZ97rH3euP8Z2+uTZH+AIy1Wm1WXHWOeYB8DgvYTFkQV/YOWsrDufyT7IaTTaefaRWMLbULbUD3LHi3ASPuOPFagmx+lkDAAOyAu1Xwrk10Pcmj7yBJBfvVmA82D1e5xDOBJVr1dvCB5UkB8il/kq5nuE+dxGC1YCaNFpURIF0TcBR+36XtBpWy/Q6N+UTLCUKPCF8tISMoUKLtpP/vt7+Y0TTIXuLD+MUDjorYl2jY9nyJfdD1AzfQlo5D8RAyFtyKGVPwlarg/zNqsM06GQpN8dqmfUQf+G7WnxuYcDf5WF4srjQ+kTdPhAWP5bUkNVy6tNRxuDuB4Hx5SKFd9W1upvvpG6LW7Ft2xJXnlY/W+DkDnqfXkyWRLKLfs7KefELPO5pUq2//z5SvUxHrUzQC3Der61eZv2PYTwr9mFWWKEgROwo0zNWVqlVZoJtP8FgqMyPJORirIq1JVAblOQU90Lj+VX9u
    username: AgCLo3/uEg2r5OJ3f/PPlCwnV/HWNxEKLdf4ulSCnFunv5mWLcqWvpozgMTkjCjKeRKN321xxCNbq8LWc7YdmOM8T7uhN9SoSMj25w2AciqoJrgCzzqTxBmnc3l2XYMqXnvPGKQ+VzfaGO5Am4p/3HUy6k0FwVpOzjlo/OkrzktQTAkZqbIu922VB4wOWNKF6sZXD5/Koo1a6Wb42BlspG41PMzyvlqiueWgwKeuatGEvxtvbZri9N/bENs7MGWlYje7AL28ceTkmzelDWz3oTOOthOaCkQ2ej7HzLN4P0efnw8wJl1+3N2K+XW5CWgd8GU27mHSrsgnrQrE3lvX9Gt3+JtQEUsc8/mHC6BfhcS0JkRboSqptI0CETgBjOcoN/UdjZiLcNx4TC2q/Aic1ex1xMlET0S8tzvWGY01RNg5N8Ovtt/omyr7i8CBIdSrpt6QS+Q0WXpF+k5wAUEkqTT5ZeFVmxgRJ0yBDby5e5EYzOHOshjDACSUiiIP/XDG2yDYROQV1lBkwqDi9OSXiI/ZmOGCKIqxedCS8OBbESMrepG2TGibLDaZCJpdz7x0GLIK7C99lu6lbkMukhcZR4YpIdltwOnxh6CRSnT1RfESSHifoB3iwndAPNWF20KTrTgN3VJ2Phtg/d76ZRfyDdzZfjrf+CXHZSEXQBuwO3AM4JwAYV35UjKE4/6/QOBWwjPURGinvB8/RvpNd0xk
  template:
    metadata:
      creationTimestamp: null
      name: pg-user-credentials
      namespace: auth
    type: kubernetes.io/basic-auth
