---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-superuser-credentials
  namespace: pocket-id
spec:
  encryptedData:
    password: AgCDaY9U4y+YHHJM78qg+sJWJnSroiglt+j5IBUlNuaI4HmhBMFR/PQfdtOFbuIZjvcYbzYyzzqg9f5jFRodvE6LJDdo+Mvas/Vx9GPca5jv4+TXTpyhL+D0yIHSm9/6h4+tqOQycaTslC27lYMvN5YPODm2E+JjkgegX+nD083hV9GNgnussQBBFCFlEqcJ0nOQ3VueVl7cdTSfktc0gT7cyDvuizt3qkaxS3xgvpx6/G+lDL/d+kBxseLNQ3ToWDscJc1tX1ObAMm3NiQtna+RmarTjSjdnPjqiYvdDP6Q1coYV+V7PAzrUJdlucKzohk/l/beDuczP1ysbF2ZPCQHKtWIry1ru+p3XbDGHk7bAnnjpmDVBOFGOhlfwescq9h+g5UB6DZVrpfjd+O+5TFZAtj7TaHJbYlQ0yIitN93mGt5wuceZ6C4BWqw0yfgi9+oaCXkVLCWIGQyUvupyzuL+i3KQevUII5gAB1YcLjOAlWe+c/kkqXnDhJI4TAlJnJooCmjf/qvGL/jFzp0HCKH+dkXjzDH61ihknwe36AV8C3OQ2laAqOVxoxJMAJTget4SiGhbAUn1yivTO7k7pygB/EMswskw/fSV60dABfLVic/AIQarUSLi2jhIy3KA32/FkTfrXc9YrXwEKhnGsSX1RLTnPzUTCitjHXsmqi5+/zDNFeFq8pBiOjmNaJveER+6g8DDJhHxkrLkU7+jl67+drxyDxUhFhHpVSXH/WV
    username: AgA73W2/4FrtNzy1Dnn9FpppaXStJRDG6Fl+M9l+F92TpFIss9hkopgq87C8mAvzrz4tWUBpgNAS9CYUyEf6jPcqHFmfAoB6CZZ/2U5INhVuDJqFEUb7f82sXLmwvGo0fUwSQ9MuMHxMA/YzZtFmGymyUzSRU9UDZtBnKQtIOv9j2eIpsBxv9jFHFhRb98w8ZCW+Dph0PyTYMG6eNZJ3EwRr3/XTtPxhj6+vvYNhdBbBPKtHZEFxtENWhAGgG/a920r3WkCdX/OHVqsCIvRG57zHzKzsncdnS8fU+8lIZt0gtqg38zIIWz2AWpp92a3QNYKK7HMS/1A0kqFc6nxrEQcDZEqbgNNYzOoX+Ft3W+NgrCtyaN5Z/AkvaWLyL6bHf902CKdIKZ2EolHR2cXsCMxAwof2GANPha2YPNXu0KoBzMV42UBy+0WFDrF1VJ6q5ExqV8Z4Pm1fTaQWqsZ9b9/RSga+Teh1adpZ2Du2cC6Gp0TlotYH1M5kvPmKQruuvmGSwwjv9oR9/tOz/BeUtgrP12gK2jKi+p3ieNJ1yyIiiXJa2bLTlfhvMHf2jGn6+019vgXX6H1BaF7EEAPZuVsd99OF7DroEP6pEm45WfGSU7fawSc8HVQODD0e0k5hqYkhzllJh570pmvEj/IX/FpFEBOxWQJnkT3A+I/szs9BH0/dCagdni96Q5jQ3S5Pg/IsRgpjNUGrJQ==
  template:
    metadata:
      creationTimestamp: null
      name: pg-superuser-credentials
      namespace: pocket-id
    type: kubernetes.io/basic-auth
