---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pocket-id-secrets
  namespace: auth
spec:
  encryptedData:
    encryption_key.txt: AgBVH2mCaRP97jJ16pIxqqXES69/nIZ8CAOOzsmk7/HPgQyr2JOm3iRs+Rc8z2tO+vtDF+F8KBTv+iZoeT4O24YberBBdawJpgHswK5uFpNIwGsuxhYt9nFg7+gGTuFrRfbQOvk4QCVjQwByF095eHam1a6+WtPqzRtSimPobmbOUpM4xog3UNCs4Gc/CsXNiVHPJtLieMS3HLYxjcH08OEEU6UqvdIXX9nPVGyUC0lRA+S/vu8A0oW5f+O//AwbxHV041yq10fa48M0GdrD5LozCNXSJymbENoN9XuLpLW18X9WIdtRWVdswgoy9pPw/3h1MDWZeblGxngeRwfjlps5b6Sg/YFBKlJ5KWGFC6uMW567UHqo5uxcqZHhlsfx/0gt9GO3jKsaWTb93hRd8duqx8EOjuu7hpIJGgt+MVEtCWetZ27tgtg1j6y2GpTLjEuQZZOVsKBwFGDurR5wtr+5L7hO3VutY3P0cbJ1JWakk77nigJL8DbYz0+dtUgt3g74ZEMlwj9Zytb787Zv3y87KY+ZVCfVWUeHmLCo4XEGKVoEEuj4VirjH7a80NYdBi7EGYeZPxNbern5x0TKmW56/ytlV+tqIZtw6U3no/sMboDJh1d4dGyUcdCZnjC130R1rGG50N5aUPXWnStsRKjHjVL7I9GbN9wHsS7XhcZKKiVQFCAIKzbZBSf8V2WJfN0OsvR90l+TGVjBpd7lHauDFiA5QIdVsnmNhv7kt1vrX7D52SjVXMV9eIjoSw==
    maxmind_api_key.txt: AgDAyoyjLHWZyj3tqlwtbZyfn6IfVZGmd9VOXJ5+Zz5wQj6P02qUipAoc+CmzcWQt4Ga9foGz2Jmvirmu5Y7D/Xn5uoj+rEasgxsbnH79xhk5xVdHXuLBWEoVne9b9zBihJE+Ellm67VK67CqLWtInBiJUExauAHN+uVuaBhuWmde3xCukTxOdgfiPV33UwgtyO9Tdytxmt0CahDSF6HdSQgi0hFIeTEJ/UM7WNZ4zikfsQYqAK173sZnZepKzoIAQkfnFtjJkW53YlCTdalsnOG6VBm7hTQTq42LxXzUYHxLoTE3oqYRSvsbq7zgv7h4fkTBojS9aCibzwkx3/RiSOs6N9g4jhheA3I8OzaU4Z7Re+ynxNWs1CpyCHIMphk2uZBCdCjIQNH1aU94Dg8HrUbAcV+bQNX6afEO2aeoMQlhQliH9oATFdvcaEAq1IMOgBuv4Gdx0ZmI4TuD2TxhmkrzZYX3VRN6nYxnvq7NlKedFXxeRb5t3rY8BDesnt/IQHTcA7IiLdMmufLjANEJEv9nHSouGG/arDsvkk7mbyt2vNP2GxO5I4bnCwOGyejaqJqw9Mj16eCv1exASdZXTR24yGZ3/T6sVqo46s5ya49ip6zhQsye+aqcmf4sS0kp0WysA8hjPy0evLU02rR/KUHhSf8gA6+bfcVKN4c3hQgwcA8Xgi7sLzRjvaQD3yiB5GPrLKmZewUNbME3qvXZH3mVi2sactGE6EvoV4L6hyr5ljcGYRZ/FBM
  template:
    metadata:
      creationTimestamp: null
      name: pocket-id-secrets
      namespace: auth
    type: Opaque
