---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pocket-id-secrets
  namespace: auth
spec:
  encryptedData:
    encryption_key: AgBGFPqlrnEjNyFDWnskIBbkdBWqsvCGtjiahfih6UcxWAmpbPKePRSgTZun8wU01gguoUsqDOPENk//pygD/fOFmf7fSlG7QthPR6MYBk1goAXtnbhqkvbOl/7ThEdPDIJMsbDc1UUU/JTvN0Wz9WYWBD+BZbY7ofja8qrX/hFV2JWGhWMH08ZPRaZI97JOgrVhtGpddFhJLoh/8/FfVM0MyvCpr2GqLHjqbCxLBNcDHnT5EK/su+nptD6+CCrOVkKsF48axBvp+XmhbjCttl6XksqUqPxFaaB+KmwharDihpxpXQtUmrwCEmHHbWGzwxmDm8Wpdczk341ZxR7aoQ09TU1HN/1bUgdAEvlReYXQgelNXjP7/MH1Z6ou21xpPNgbWNxMVVeNUaxkK2Ex5hPsoXt4uVgvsBwAl2JhndIpXrWRoKvMfpc5An4+xcxTUyptMYxXIOcedXJwi4TJovc9T/1p7XIl/G0h3ynUDaMdFNl/PrSGIC5piD4z5v0b5I468wqxsfiC4esHoBz7VpD5nmHe7eCsf1AqXiSfZLsRnr8tJR+WfNYSdycDVIUrBYpAw6RLDXnL4Lvyb1BL2HNg9wM1+9jeDb9ZpRWBq5h0iRAzphjEKL1r6rcP+5rJULjdtt3UMKrR3lt9kFXSU2Rl/DUMG5KT9WgbOMAEBoe6CZY1Urn+pG+rN55PPmRYhU3soHpz0oWSpWteK+rq4VZClsuLja48V/CnMVcjEIIsCIvkp+i5BqwFer0+yg==
  template:
    metadata:
      creationTimestamp: null
      name: pocket-id-secrets
      namespace: auth
    type: Opaque
