---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pocket-id-secrets
  namespace: auth
spec:
  encryptedData:
    encryption_key.txt: AgBXS9sj+Y+x/5QdfW15KuWvcw9TprdMpfO4HIwbxWLE1eeoY4pnXRjFH6He/Q8BQLOodtiyRyNhpMSlzdoI4j/CrjurEh+ciC1RLR1DoVcivdDpl5DxcllJtgHhweFxDLb5seCNSrvOofgxOl8F1wLZMiNB9f7VWKhvtg3s39tv+LfeLH4nonAmXEB6jX7NF5MlxOrSP7Vr7q5JKvag/N5LMtKE5sY1D5ka7iRagnfJPs2pz2JWxx4A73prurr5Egu1NZCljyIA/p8FiZY1ZEcRtSfuw5MBTMBh5Gh/y8Znic7LyWzxJZ41gaodIsJJtA5x3Hy/B2RuWlwn8YyBaja+UABbowixCtU2o807Eu2bNAYWemnZrKD15u/KkhpPjzHlTp4Sh+RNmA43/cpJkIPkK2/IJ+MX+Er4oHg06WJzmLJsiidJgJHPuMgUCZFIcoqe3ESzs3Tp4CuDHoDoIP5XaKtwA+ic74yGb5WIXM1RV520A6ATc5PwdZ6X5mTgLWK3uOBRh6kk1zmuGqc+BIuykUKef/TbGAA2zG1J6DIiGWJ3D/b0bHp8xgSJlVQCX+NXpOTlnyI0qCl/S4zTrhlsbTt+6P+DJNzZNxPnAiX83q6Fwv5en3S3IF6GFEyLwt+JNaTU0OyBJR6jLKibQe5H/l4ogTMSQ9ksQ8H7MKn9/FJF9iTBN2OMyKi0BiE1A4yvaQYdz7KrNJLGbdeQxffKhO36ULf5DZvUkZNU+FR3bhAc6dDluKJwxlVLdA==
    maxmind_api_key.txt: AgBVPaDAQrxeRuW0al4PBGt5TqI0dJAEHaDHE+YEQWpGMVOwBK22Lomf26WcQ0qc9J7yTi/2yFh8LWAW5DZBhlhKqM+yXbrNDi3VrNkG7bso9nF7H+8XfB8KUAt6/QVuNlkGHS5roTAWkNkY3dz4hVSpElBZOocu40w1CsFDswIjtTYvV/Exh1g26s58TZ61xafJZzukqKEW21q2lz/vgA2YpnX5p1ZyKCboVLMr4uEwTd1gxusImZa0dS8LvQxVH2bZxJXbUR9y7eK4A+eAtopgCmxwOPfrzxRQoJSrtv9fXx48jTOhpnz8JC6V2DSzIF9Gfppw992pyq/ZShymGJreN9T1GSQF4eOrmrnwlLu2NcAMCndNS2vEbu8Qaek0quy5H2VZnnPJVB8TSBO0OpdtRIel89dKNEdCQLQDZXr3XZv5Z5iBUywCb66l+26a2JBi5YAQkVwh+fg6WiXc6doOw6QvipflzMVjo1/TzOQbUnG3oK2OlnaqK4/2b0tDEhoHy9vNV5+zo+goYjIaJyCfXxSDldAjunptPuhNJf4vlLF5Ck5BWTbr8n1Pn6pP+3oATdu/6TdEEaisf14vXXvBfuOiziJp11ZYWxfAAEjhtMEqUDWFef9x5vHFPV9N7sJujmL+me9CR3fZXNdv+w1OU4UINDeZ1JXS9j+8c+82BxrWEeiM66xESOMKje6F7g0XOKQVhGaCAnhWMPRVIZ1zRPpSDJEZxMUquywSVqomfEEtNI+TYKVq
  template:
    metadata:
      creationTimestamp: null
      name: pocket-id-secrets
      namespace: auth
    type: Opaque
