apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pocket-id
  namespace: auth
  labels:
    app: pocket-id
spec:
  selector:
    matchLabels:
      app: pocket-id
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
