apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: flaresolver
spec:
  type: ClusterIP
  selector:
    app: flaresolver
  ports:
    - name: web
      port: 80
      targetPort: flaresolver
