apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: dns
spec:
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      # securityContext:
      #  seccompProfile:
      #    type: RuntimeDefault
      containers:
        - name: unbound
          image: docker.io/mvance/unbound:1.22.0@sha256:76906da36d1806f3387338f15dcf8b357c51ce6897fb6450d6ce010460927e90 # renovate: datasource=docker depName=docker.io/mvance/unbound packageName=docker.io/mvance/unbound versioning=docker registryUrl=https://index.docker.io
          # securityContext:
          #  allowPrivilegeEscalation: false
          #  readOnlyRootFilesystem: false
          ports:
            - name: unbound-dns-tcp
              containerPort: 53
              protocol: TCP
            - name: unbound-dns-udp
              containerPort: 53
              protocol: UDP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          startupProbe:
            exec:
              command: ["drill", "@127.0.0.1", "-p", "53", "cloudflare.com"]
            initialDelaySeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /opt/unbound/etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: config
              mountPath: /opt/unbound/etc/unbound/stub-zones.conf
              subPath: stub-zones.conf
      volumes:
        - name: config
          configMap:
            name: unbound-config
