apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: monitoring infrastructure
  sourceRepos:
    - "https://github.com/cedsbe/home-infra"
    - "https://prometheus-community.github.io/helm-charts"
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "default"
      server: "*"
    - namespace: "grafana"
      server: "*"
    - namespace: "kube-system"
      server: "*"
    - namespace: "kubelet-serving-cert-approver"
      server: "*"
    - namespace: "monitoring"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
