apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: arr
spec:
  storageClassName: proxmox-csi
  volumeName: pv-bazarr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
