---
# Base Linux role handlers

- name: Restart ntp
  ansible.builtin.service:
    name: "{{ 'ntp' if ansible_os_family == 'Debian' else 'ntpd' }}"
    state: restarted

- name: Restart sshd
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: Reload firewall
  ansible.builtin.service:
    name: ufw
    state: reloaded
