$ANSIBLE_VAULT;1.1;AES256
38613666343234373938623236313166356435626335343534653635303230333865653463386565
3462353663666238363833316263303465363362356365340a306365386139313035343839636136
35333332393232373832646632613738616364393733633031633532653431323035353130396338
6532303562323362620a363033386161386661383633323862363665356565343232623039616633
37636131373366303531623933363639343465376265386234366639313966313938656364373633
38323531376536643533633638313761323362376662306636363166313866323637666564363366
62376439383435333966636135636431313135383535303036393863616465306363623466313930
65323362323363643536373932653664633263663537333031333662666330356135663066343765
35633234353831373334633638386130623966323635663837393736303133663237
